### ISSUE TITLE
end to end testing does not work on windows

### ISSUE THREAD

**Issue by vinaydate** [angular/angular-seed#176]
I am new to web development and angularjs. My OS is windows 7.  I followed all instructions in 'readme.md'. I am through upto karma tests. But could not get through the e2e testing. The 'npm-debug.log' file says:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 verbose node symlink C:\Program Files\nodejs\node.exe
5 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
6 info preprotractor angular-seed@0.0.0
7 info protractor angular-seed@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-seed@0.0.0 Failed to exec protractor script
10 error angular-seed@0.0.0 protractor: `protractor test/protractor-conf.js`
10 error Exit status 8
11 error Failed at the angular-seed@0.0.0 protractor script.
11 error This is most likely a problem with the angular-seed package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     protractor test/protractor-conf.js
11 error You can get their info via:
11 error     npm owner ls angular-seed
11 error There is likely additional logging output above.
12 error System Windows_NT 6.1.7601
13 error command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "protractor"
14 error cwd G:\Vinay\GitHub\angular-seed
15 error node -v v0.10.26
16 error npm -v 1.4.3
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

**Comment by eebann** [comment]
i tried running npm test and it show npm err.. after some long codes ..i am new to angular pls do assist me thank you

**Comment by petebacondarwin** [comment]
@eebann There are many reasons why the `npm test` could fail. It is impossible to help without more information.

**Comment by eebann** [comment]
am learning how to use angular seed , i downloaded the zip file then used the npm test as directed ..this is what i get which doesnt look right [:( ]
![q](https://cloud.githubusercontent.com/assets/8550501/13528718/d35247b4-e20f-11e5-8073-3f32081e9c61.JPG)

**Comment by petebacondarwin** [comment]
It looks to me like you are trying to run `npm test` from outside the project folder. Try `cd angular-seed` or whatever the name of the folder containing the project is called.
