### ISSUE TITLE
npm install fails on bower (post)install (Mavericks 10.9.3)

### ISSUE THREAD

**Issue by arti040** [angular/angular-seed#196]
Yep,
my terminal throws this:

<code>
<pre>
bower angular-route#1.2.x       EACCES EACCES, open '/Users/arti/.cache/bower/registry/bower.herokuapp.com/lookup/angular-route_e3ac2'

Stack trace:
Error: EACCES, open '/Users/arti/.cache/bower/registry/bower.herokuapp.com/lookup/angular-route_e3ac2'
</pre>
</code>

AND this:
<code>
<pre>
npm ERR! angular-seed@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 postinstall script.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.2.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/arti/websites/angular-seed
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/arti/websites/angular-seed/npm-debug.log
npm ERR! not ok code 0
</pre>
</code>

**Comment by rasekar2000** [comment]
Same Error.. Any suggestion to resolution will be highly  appreciated.. 

AcumenSekarPro:angular-seed rajacumen$ sudo npm start
 
> angular-seed@0.0.0 prestart /Users/rajacumen/Desktop/RajAcumen/DDrive/Personal/acumen/BigCommerce/LookB4BuyApps/Structure.Ang.Seed/angular-seed
> npm install

npm WARN cannot run in wd angular-seed@0.0.0 bower install (wd=/Users/rajacumen/Desktop/RajAcumen/DDrive/Personal/acumen/BigCommerce/LookB4BuyApps/Structure.Ang.Seed/angular-seed)
 
> angular-seed@0.0.0 start /Users/rajacumen/Desktop/RajAcumen/DDrive/Personal/acumen/BigCommerce/LookB4BuyApps/Structure.Ang.Seed/angular-seed
> http-server -a localhost -p 8000 -c-1

/
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)

npm ERR! angular-seed@0.0.0 start: `http-server -a localhost -p 8000 -c-1`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 start script.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a localhost -p 8000 -c-1
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/rajacumen/Desktop/RajAcumen/DDrive/Personal/acumen/BigCommerce/LookB4BuyApps/Structure.Ang.Seed/angular-seed
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/rajacumen/Desktop/RajAcumen/DDrive/Personal/acumen/BigCommerce/LookB4BuyApps/Structure.Ang.Seed/angular-seed/npm-debug.log
npm ERR! not ok code 0
AcumenSekarPro:angular-seed rajacumen$ sudo npm start

**Comment by pejman-saberin** [comment]
I replaced the content of package.json with the following and that solved my issue: 

{
"version": "0.0.0",
"private": true,
"name": "angular-phonecat",
"description": "A tutorial application for AngularJS",
"repository": "https://github.com/angular/angular-phonecat",
"license": "MIT",
"devDependencies": {
"karma": "~0.10",
"protractor": "~0.20.1",
"http-server": "^0.6.1",
"bower": "^1.3.1",
"shelljs": "^0.2.6"
},
"scripts": {
"postinstall": "bower install",

"prestart": "npm install",
"start": "http-server -p 8000",

"pretest": "npm install",
"test": "karma start test/karma.conf.js",
"test-single-run": "karma start test/karma.conf.js  --single-run",

"preupdate-webdriver": "npm install",
"update-webdriver": "webdriver-manager update",

"preprotractor": "npm run update-webdriver",
"protractor": "protractor test/protractor-conf.js",

"update-index-async": "node -e \"require('shelljs/global'); sed('-i', /\\/\\/@@NG_LOADER_START@@[\\s\\S]*\\/\\/@@NG_LOADER_END@@/, '//@@NG_LOADER_START@@\\n' + cat('bower_components/angular-loader/angular-loader.min.js') + '\\n//@@NG_LOADER_END@@', 'app/index-async.html');\""
}
}

**Comment by PratibhaMishra** [comment]
Facing same issue, any updates on this issue?

**Comment by gkalpak** [comment]
This has turned into a kitchen-sink for all sorts of different errors.
I'm going to clode this. If anyone is still having problems, please open a new issue.
