### ISSUE TITLE
npm install report error 

### ISSUE THREAD

**Issue by johnwonder** [angular/angular-seed#198]
npm ERR! Error: No compatible version found: http-server@'^0.6.1'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.3","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6
","0.2.9","0.3.0","0.4.0","0.4.1","0.5.0","0.5.1","0.5.2","0.5.3","0.5.5","0.6.0
","0.6.1"]
npm ERR!     at installTargetsError (D:\NodeJs\node_modules\npm\lib\cache.js:685
:10)
npm ERR!     at D:\NodeJs\node_modules\npm\lib\cache.js:607:10
npm ERR!     at saved (D:\NodeJs\node_modules\npm\node_modules\npm-registry-clie
nt\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)

**Comment by gkalpak** [comment]
This is probably not an issue any more :smiley:
In any case, all dependencies have been updated in #341, so any version-specific issues should be solved.
