### ISSUE TITLE
error on npm start

### ISSUE THREAD

**Issue by PrasadHonrao** [angular/angular-seed#199]
Steps to reproduce
1. Clone angular-seed repo
2. Install dependencies using npm install
3. Try to start the server using npm start.

![angular-seed error](https://cloud.githubusercontent.com/assets/1454174/3274376/71271d0c-f32e-11e3-9f99-339f40d12132.PNG)

Below are log file [npm-debug.log] details

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart angular-seed@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info angular-seed@0.0.0 Failed to exec prestart script
9 error angular-seed@0.0.0 prestart: `npm install`
9 error Exit status 1
10 error Failed at the angular-seed@0.0.0 prestart script.
10 error This is most likely a problem with the angular-seed package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     npm install
10 error You can get their info via:
10 error     npm owner ls angular-seed
10 error There is likely additional logging output above.
11 error System Windows_NT 6.2.9200
12 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
13 error cwd C:\$\Code - Git\Open Source\angular-seed
14 error node -v v0.10.28
15 error npm -v 1.4.9
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by im-auld** [comment]
I encountered an error on startup as well. Output:

```
chrubuntu:angular-seed user$ npm start

> angular-seed@0.0.0 prestart /home/user/projects/angular-seed
> npm install


> angular-seed@0.0.0 postinstall /home/user/projects/angular-seed
> bower install


> angular-seed@0.0.0 start /home/user/projects/angular-seed
> http-server -a localhost -p 1337 -c-1


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRNOTAVAIL
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at net.js:1143:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)

npm ERR! angular-seed@0.0.0 start: `http-server -a localhost -p 1337 -c-1`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 start script.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a localhost -p 1337 -c-1
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.8.11
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/user/projects/angular-seed
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/projects/angular-seed/npm-debug.log
npm ERR! not ok code 0
```

I tried changing the port number in `package.json` as noted above but that did nothing (I tried 8000, 5000 and 1337). Changing `http-server -a localhost -p 1337 -c-1` to `http-server -a 0.0.0.0 -p 8000` got the app to start. I am running a chroot on an HP Chromebook so I imagine the unorthodox installation on Linux has something to do with it.

**Comment by ummahusla** [comment]
I had this error, when I've tried to run angular-seed project for the first time. I've closed all other terminal windows, deleted the angular-seed and cloned it again. After that used `npm install` and `npm start` and it worked for me.

**Comment by winnietong** [comment]
I've been struggling with same error too. Seems like this error happens whenever I try to run my server from an already open port, so I ended up getting a list of the processes and killing it. Took me a while to figure out what was going on, but here's what I did to fix it:

I got a list of open processes on a port, use 'sudo lsof - :port'. For example, for port :8000: 
```
sudo lsof -i :8000
```

Then I killed the process using the listed PID:
```
sudo kill -9 PID
```

Thats it - hope this helps someone!

**Comment by caiqinzhou** [comment]
@im-auld : I have got the same error, and fix the error with your answer, thx :+1:

**Comment by jwineman** [comment]
Fixed by uninstalling and reinstalling npm
sudo npm uninstall npm -g
brew install npm
npm install

**Comment by skananitos** [comment]
I had the same problem when I tried `npm start`. The solution that worked for me: http-server needs to be installed globally with `npm install -g http-server`

**Comment by GitKou** [comment]
I had the same problem when I tried npm start. The solution that worked for me:delete the existing "node_modules" files, the clean the cache:  npm cache clean

**Comment by Pengfei-Gao** [comment]
open the terminal,execute "npm cache clean"

**Comment by fredpedro** [comment]
Thank you @skananitos, I installed `http-server` globally and it started a server.

**Comment by csejanath** [comment]
I got the same error. Later I open the terminal in administrative mode in Windows 7 and then it works fine.

**Comment by gkalpak** [comment]
Closing since the OP was able to solve the problem and other issues seem to not be related to angular-seed itself (but rather `node`, `npm` or firewalls).

**Comment by TASTYCS** [comment]
hey guys ,
 I AM ALSO FACING THE SOME ISSUES CAN ANYONE HELP HOW TO FIX IT.
![image](https://cloud.githubusercontent.com/assets/19873650/26782448/494220e2-4a11-11e7-9e70-d982e02573f2.png)

**Comment by TASTYCS** [comment]
HEY GUYS, I AM ALSO FACING SOME ISSUES CAN ANYONE HELP IN FIXING IT.
![image](https://cloud.githubusercontent.com/assets/19873650/26782540/b9a6eb74-4a11-11e7-9dbd-e3a10e42ce68.png)
