### ISSUE TITLE
Comprehensive AngularJS starters comparison

### ISSUE THREAD

**Issue by dancancro** [angular/angular-seed#203]
Hi group,

I made [this comparison](http://www.dancancro.com/comparison-of-angularjs-application-starters) of things people can use to start a new AngularJS app and angular-seed is one of them.

It is an editable spreadsheet so your corrections and additions are welcome.

I have one question in particular.  What exactly does it mean to load AngularJS asynchronously?  I hadn't seen that one before.

One other question... Would it be possible to put a prominent link to this comparison on the angular-seed home page so that people can make more informed decisions when choosing the foundation for their projects?

Thanks,
Dan

**Comment by gkalpak** [comment]
I understand this is pretty old by now :)
The problem with such comparisons is that they tend to get outdated in the blink of an eye.

--
To answer your question anyway, asynchronously loading the angular scripts means loading them in a way that doesn't block HTML parsing and rendering (as normal `<script></script>` tags do by default).
This is made possible using `angular-loader`. Another benefit is that the load order of scripts doesn't matter (as long as `angular-loader` is loaded first (often even inline in `index.html`)), so you don't have to block the execution of a mdules script until the core `angular.js` file is loaded.

TBH, with the rise of bundlers and build tools these days, there are several alternatives for efficiently loading your JS.
