### ISSUE TITLE
error when doing npm run update-webdriver

### ISSUE THREAD

**Issue by bargitta** [angular/angular-seed#212]
Here is the log when dpm run update-webdriver

Updating selenium standalone
downloading http://selenium-release.storage.googleapis.com/2.40/selenium-server-standalone-2.40.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.9/chromedriver_mac32.zip...
-

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

npm ERR! angular-seed@0.0.0 update-webdriver: `webdriver-manager update`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 update-webdriver script.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webdriver-manager update
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "update-webdriver"
npm ERR! cwd /Users/xichen/Documents/angular/angular-seed
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
-----------------------------------------
Any idea about that?

**Comment by Measy** [comment]
still have the problem

**Comment by mnemanja** [comment]
I have the same error:

    npm ERR! node v4.2.1
    npm ERR! npm  v2.14.7

    npm ERR! missing script: update-webdriver

Shouldn't the update-webdriver come with protractor?

**Comment by petebacondarwin** [comment]
Try running with node version 0.12.x and npm version 2.9.x

**Comment by mnemanja** [comment]
Not really an option for me at the moment, but thanks for the suggestion.

**Comment by petebacondarwin** [comment]
@mnemanja Have you tried https://github.com/creationix/nvm

**Comment by Measy** [comment]
hi @petebacondarwin  , I have npm version is 2.11.3,node version v0.12.7, may it effect the result?
I got the err as follow:
D:\Code-git\angular-phonecat>npm run protractor

> angular-phonecat@0.0.0 preprotractor D:\Code-git\angular-phonecat
> npm run update-webdriver


> angular-phonecat@0.0.0 preupdate-webdriver D:\Code-git\angular-phonecat
> npm install


> angular-phonecat@0.0.0 postinstall D:\Code-git\angular-phonecat
> bower install


> angular-phonecat@0.0.0 update-webdriver D:\Code-git\angular-phonecat
> webdriver-manager update

Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.j
ar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.19/chromedriver_win32.zip...
Error: Got error Error: connect ETIMEDOUT from https://selenium-release.storage.googleapis.com/2.47/
selenium-server-standalone-2.47.1.jar
Error: Got error Error: connect ETIMEDOUT from https://chromedriver.storage.googleapis.com/2.19/chro
medriver_win32.zip

> angular-phonecat@0.0.0 protractor D:\Code-git\angular-phonecat
> protractor test/protractor-conf.js

[launcher] Process exited with error code 1
D:\Code-git\angular-phonecat\node_modules\protractor\node_modules\q\q.js:126
                    throw e;
                          ^
Error: No selenium server jar found at the specified location (D:\Code-git\angular-phonecat\node_mod
ules\protractor\selenium\selenium-server-standalone-2.47.1.jar). Check that the version number is up
 to date.
    at LocalDriverProvider.addDefaultBinaryLocs_ (D:\Code-git\angular-phonecat\node_modules\protract
or\lib\driverProviders\local.js:37:11)
    at LocalDriverProvider.setupEnv (D:\Code-git\angular-phonecat\node_modules\protractor\lib\driver
Providers\local.js:71:8)
    at Runner.run (D:\Code-git\angular-phonecat\node_modules\protractor\lib\runner.js:261:31)
    at TaskRunner.run (D:\Code-git\angular-phonecat\node_modules\protractor\lib\taskRunner.js:123:19
)
    at createNextTaskRunner (D:\Code-git\angular-phonecat\node_modules\protractor\lib\launcher.js:22
3:20)
    at D:\Code-git\angular-phonecat\node_modules\protractor\lib\launcher.js:246:7
    at _fulfilled (D:\Code-git\angular-phonecat\node_modules\protractor\node_modules\q\q.js:797:54)
    at self.promiseDispatch.done (D:\Code-git\angular-phonecat\node_modules\protractor\node_modules\
q\q.js:826:30)
    at Promise.promise.promiseDispatch (D:\Code-git\angular-phonecat\node_modules\protractor\node_mo
dules\q\q.js:759:13)
    at D:\Code-git\angular-phonecat\node_modules\protractor\node_modules\q\q.js:573:44

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\
\bin\\npm-cli.js" "run" "protractor"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'
.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Code-git\angular-phonecat\npm-debug.log

**Comment by Measy** [comment]
It seems err while run webdriver-manager update which resulte in the follow errors

**Comment by ivannugo** [comment]
WIndows 7 workaround in package.json:

"webdriver-start": "cd node_modules\\protractor\\bin\\ && webdriver-manager start",
"webdriver-update": "cd node_modules\\protractor\\bin\\ && webdriver-manager update"

**Comment by gkalpak** [comment]
Fixed in #341.

**Comment by petebacondarwin** [comment]
So we should close then @gkalpak ?

**Comment by gkalpak** [comment]
I would if I had the rights :smiley:

**Comment by petebacondarwin** [comment]
:-( - we need to get @naomiblack on the case there. closing
