### ISSUE TITLE
getting error while running npm install

### ISSUE THREAD

**Issue by jpatel3** [angular/angular-seed#215]
while running 'npm install' I am running into following error -

npm http GET https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/protractor
npm http GET https://registry.npmjs.org/http-server
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/karma-junit-reporter

npm ERR! Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:483:26)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR!     at CleartextStream.ondata (http.js:1150:24)
npm ERR!     at CleartextStream._push (tls.js:375:27)
npm ERR!     at SecurePair.cycle (tls.js:734:20)
npm ERR!     at EncryptedStream.write (tls.js:130:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!     at Socket.emit (events.js:67:17)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/Jaimin/Apps/Github/ang/angular-seed
npm ERR! node -v v0.6.15
npm ERR! npm -v 1.1.16
npm ERR! message SSL Error: SELF_SIGNED_CERT_IN_CHAIN
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/J/Apps/Github/ang/angular-seed/npm-debug.log
npm not ok

**Comment by gkalpak** [comment]
This wasn't related to `angular-seed`. It sounds like it was either `npm` or `phantomjs` related.
