### ISSUE TITLE
bower install freeze on boilerplate 

### ISSUE THREAD

**Issue by neoswf** [angular/angular-seed#220]
Running a fresh install of ng-seed.
After executing `npm install`, than bower install starts, and than it freezes on boilerplate. Stuck and not progressing.

`bower validate      4.3.0 against git://github.com/h5bp/html5-boilerplate.git#~4.3.0`

**Comment by gkalpak** [comment]
Closing as this is pretty old and there was no response from OP (so hopefully this is not an issue any more). If anyone is still having problems, please open a new issue.
