### ISSUE TITLE
The web content is blank in browser after clicked url view1 

### ISSUE THREAD

**Issue by xinshouke** [angular/angular-seed#227]
I started the web server the command 'http-server -a localhost -p 8000', and I went into path 'app',
then I clicked URL view1 , the web content is blank!  The URL in browser is 'http://127.0.0.1:8000/app/#/view1', as I understood, there  should be the words 'This is the partial for view 1.'  Looks like I mistook something,shouldn't I?

**Comment by vgrazi** [comment]
@petebacondarwin your step cd angular-seed/app did not work for me, 
However cd angular-seed did work.

**Comment by xixo1983** [comment]
sudo bower install --allow-root
