### ISSUE TITLE
git clone with project name and depth=1

### ISSUE THREAD

**Issue by santiagobasulto** [angular/angular-seed#239]
On the readme there's a standar clone. Maybe it can be improved a little bit (git beginners might not be aware of this and can be useful for them):

```
git clone --depth=1 https://github.com/angular/angular-seed.git <your-project-name>
```

Btw, sorry to include this in an issue, but forking and PRing just for this seemed like a waste of time.

**Comment by toddwseattle** [comment]
I liked the idea of this and tried it; but I couldn't figure out how to push to a new repository on github.com with a depth of 1; e.g. my flow with angular-seed is to do:

    git clone https://github.com/angular/angular-seed mynewproject
    cd mynewproject
    git remote set-url origin https://myname/mynewproject
    git push origin master

But this fails if the clone is done with level=1 on the push back to github.  Perhaps there is a workaround, but I'm not enough of a git wizard to make work.

**Comment by petebacondarwin** [comment]
If you only want to have a copy of the repository without the history then just delete the .git folder after cloning and then re-initialize the repository:

```bash
git clone --depth=1 https://github.com/angular/angular-seed mynewproject
cd mynewproject
rm -rf .git
git init
git remote add origin https://github.com/myname/mynewproject
```
