### ISSUE TITLE
How should I structure a subsection/view?

### ISSUE THREAD

**Issue by VictorQueiroz** [angular/angular-seed#241]
I'm reading: https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub and studying a couple of AngularJS projects (including this), and I got some questions about the "Angular Best Practices for App structure" guide.

"We group elements of an application either under a "components" directory (for common elements reused elsewhere in the app), or under meaningfully-named directories for recursively-nested sub-sections that represent structural "view" elements or routes within the app"

Okay, it says that each subsection/view represents a not reusable component of the app which will act as a resource like "user", "post", "fruits" etc.

Here is how I'm thinking that my app should be structured:

```
app/
  app.js
  e2e-tests/
  components/
    version/
      version.js
      version-directive.js
      version-filter.js
  user/
    user.js // angular.module('user', [])
    user-service.js // angular.module('user').factory(...)
    user-service_test.js
    user-profile/
      user-profile.js // angular.module('user-profile', ['user-profile-controller'])
      user-profile.html
      user-profile_test.js
      user-profile-controller.js // angular.module('user-profile-controller', [])
      user-profile-controller_test.js
```

Inside of user-profile.js, I'll keep the user-profile related routes, controllers etc. in a new module called 'user-profile' where I'll attach the 'user-profile-controller' module as a requirement, 'user-profile' will consume the user-profile-controller.js, which will consume the user-service.js.

Where am I wrong? I'm really confused about this, I guess...

**Comment by gkalpak** [comment]
Discussing application layout is outside the scope of this repo. This subject is more suitable for one of the [general support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

That said, there are several popular styleguides (including [this one][2]) that contain useful advice on application structuring.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
[2]: https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md
