### ISSUE TITLE
Errors when running npm run protractor

### ISSUE THREAD

**Issue by ghost** [angular/angular-seed#254]
Running npm run protractor gives errors as described here:

http://stackoverflow.com/questions/27958710/errors-running-the-angularjs-seed-e2e-tests-on-two-machines

> angular-seed@0.0.0 protractor C:\G\angular-seed
    > protractor e2e-tests/protractor.conf.js
    
    Starting selenium standalone server...
    [launcher] Running 1 instances of WebDriver
    [launcher] Process exited with error code 1
    
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: spawn ENOENT
        at errnoException (child_process.js:1001:11)
        at Process.ChildProcess._handle.onexit (child_process.js:792:34)
    
    npm ERR! angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
    npm ERR! Exit status 8
    npm ERR!
    npm ERR! Failed at the angular-seed@0.0.0 protractor script.
    npm ERR! This is most likely a problem with the angular-seed package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     protractor e2e-tests/protractor.conf.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls angular-seed
    npm ERR! There is likely additional logging output above.
    npm ERR! System Windows_NT 6.1.7601
    npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "pro
    ractor"
    npm ERR! cwd C:\G\angular-seed
    npm ERR! node -v v0.10.33
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     C:\G\angular-seed\npm-debug.log
    npm ERR! not ok code 0

The proposed solution fixes the problem. 

As this happened on two machines then I suspect it may be a problem for everyone.

**Comment by twlz0ne** [comment]
Try to add `chromeOnly: true` in e2e-tests/protractor.conf.js
https://github.com/angular/protractor/issues/187

**Comment by Baskerville42** [comment]
> Try to add chromeOnly: true in e2e-tests/protractor.conf.js
> angular/protractor#187
And check the JDK installation. It's helped for me.

**Comment by jkbits1** [comment]
I had the same problem on a fresh install of this repo, using Win 7 a few days ago. The chromeOnly suggestion worked, as in https://github.com/angular/protractor/issues/187. 

The suggestion appears to exist already in https://github.com/angular/angular-phonecat.

Thanks to the contributors who made the suggestion.

**Comment by felixzapata** [comment]
I have the same problem. I´ve added the `chromeOnly: true` but it doesn´t work for me.

**Comment by felixzapata** [comment]
Finally, I run the protractor tests adding `chromeOnly:true` and `directConnect: true`.

**Comment by sebastianrogers** [comment]
Yes the combination of

>  chromeOnly:true and directConnect:

 true worked for me as well.

This was on Windows 10

**Comment by gkalpak** [comment]
Closing as it seems to have been solved.

**Comment by fowlerwill** [comment]
Anyone that reads this and the above solutions don't solve the problem. Try updating your nodejs version. I was on 0.12 - updating to 4.4. fixed this

**Comment by dexteriti** [comment]
With node v4.4.4 + chromeOnly:true and directConnect:true =>
```
[15:22:35] E/launcher - "process.on('uncaughtException'" error, see launcher
[15:22:35] E/launcher - Process exited with error code 199
```
Additionally:

`Driver info: org.openqa.selenium.chrome.ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:138)
	... 14 more
15:21:25.815 WARN - Exception: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a),platform=Mac OS X 10.11.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'kghomac03.local', ip: '10.48.4.44', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_91'`


Any update would be great, thanks.

**Comment by gkalpak** [comment]
It seems that the ChromeDriver is missing. Maybe the file couldn't be downloaded or was corrupted.
I would try removing `node_modules/` and try again.

**Comment by clipsett** [comment]
I'm getting the same issue as @dexteriti with error code 199. 

Here is the relevant output from my script 
[15:04:26] I/local - Starting selenium standalone server...
[15:04:26] I/launcher - Running 1 instances of WebDriver
[15:04:29] I/local - Selenium standalone server started at http://10.1.1.82:59698/wd/hub
[15:04:29] E/launcher - "process.on('uncaughtException'" error, see launcher
[15:04:29] E/launcher - Process exited with error code 199

This happens after calling protractor <conf.js> from a Jenkins VM.

The interesting thing I've found is that, if I run the tests locally, without starting webdriver-manager, the tests pass. If I run webdriver-manager, the tests fail. I'm not sure what's going on with my Jenkins build currently, but it appears webdriver-manager may be contributing. Has there been any progress on this issue?

**Comment by shrikantbiradar3449** [comment]
I tried both 
chromeOnly:true and directConnect:true


but still facing the issue

C:\Angular4Demo\ng4-playground>ng e2e
** NG Live Development Server is listening on localhost:49152, open your browser on http://localhost:49152/ **
Date: 2017-09-13T09:25:50.352Z
Hash: 12ab5fd866854d91cfe8
Time: 7432ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 2.29 MB {inline} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 209 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.3 kB {inline} [initial] [rendered]

webpack: Compiled successfully.
**events.js:160
      throw er; // Unhandled 'error' event**
      ^

Error: connect ETIMEDOUT 74.125.200.128:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

**Comment by gkalpak** [comment]
This is the wrong repository. This seed project is for AngularJS (aka 1.x).
Your app seems to use Angular (aka 2+).

**Comment by shrikantbiradar3449** [comment]
ok..let me create a new issue there..Thanks
