### ISSUE TITLE
Separate Out Controllers from their Modules

### ISSUE THREAD

**Issue by daviskoh** [angular/angular-seed#257]
Adhering more closely to what appears to be the [Angular Team Guide](https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub), I have a [branch](https://github.com/daviskoh/angular-seed/tree/improvement/separate-out-components-into-files) that separates out controllers from **view1.js** & **view2.js**. However, I am not fully satisfied w/ what I did in the **karma.conf.js** file to make the specs pass and thus have yet to submit a PR. 

Questions:
1. Is there a reason why the controllers in those files were not separated out in the first place?
2. If separating them is desired, is there a recommended way of dealing w/ the load order of modules?

**Comment by gkalpak** [comment]
I assume this is about organizing your code with one directory per feature/view.
(Although I'm not 100% sure based on the title and description, this is my best guess.)

Closing as this has already been done.
Please open a new issue (with a clear explanation) in case I misunderstood.
