### ISSUE TITLE
AngularJS version in bower.json is not matching with the tutorial

### ISSUE THREAD

**Issue by et1982** [angular/angular-seed#259]
The angular version declared in the bower.json file is 1.2.x, however, in the angular official tutorial:

https://docs.angularjs.org/tutorial/step_11

...the used version is 1.3.x. 

Even in this step 11, if it is not used the right version, the example does not run.

**Comment by pedrosanta** [comment]
From my point of view this seed project should always be updated with the last stable version.

**Comment by gkalpak** [comment]
Fixed in #341.

**Comment by pedrosanta** [comment]
Thanks @gkalpak. Didn't noticed that this was still open. 😏  Cheers.
