### ISSUE TITLE
Unable to get npm install to run on Windows 7 64 bit

### ISSUE THREAD

**Issue by mongonv** [angular/angular-seed#262]
I have been trying to get my first test app going with the angular-seed on Windows 7 64 bit, node.js 10 and cannot get it to successfully install.  

I have tried uninstalling node, using 10 and 12 (12 has other issues), removing all the folders I can find relating to node, and cannot find what is wrong.

It always comes up with a warn on fsevents and a hard failure on the phantomjs stuff.  Below is what comes out on the console when I run the npm install:

E:\Development\AngularJs\as1\angular-seed>npm install
npm WARN optional dep failed, continuing fsevents@0.2.1
/
> ws@0.4.32 install E:\Development\AngularJs\as1\angular-seed\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

The system cannot find the path specified.

E:\Development\AngularJs\as1\angular-seed\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>node "C:\nodejs\node_modules\n
pm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
\
> phantomjs@1.9.16 install E:\Development\AngularJs\as1\angular-seed\node_modules\karma-phantomjs-launcher\node_modules\phantomjs
> node install.js

The system cannot find the path specified.
Download already available at C:\Users\Ed\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Extracting zip contents
Removing E:\Development\AngularJs\as1\angular-seed\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\Ed\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1427584960088\phantomjs-1.9.8-windows -> E:\Development\An
gularJs\as1\angular-seed\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at E:\Development\AngularJs\as1\angular-seed\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom\phantomjs
.exe
npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.16 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd E:\Development\AngularJs\as1\angular-seed
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

Any help would be greatly appreciated.
Thanks in advance

**Comment by gpltaylor** [comment]
try installing PhantomJS using the following -g (global) command.

# npm install -g phantomjs

Then

# npm install

If this does not work try manually downloading PhantomJS from their site.
http://phantomjs.org/download.html

**Comment by gkalpak** [comment]
Since there hasn't been any response, I assume this is not an issue any more (one way or another).
