### ISSUE TITLE
Unable to do NPM install

### ISSUE THREAD

**Issue by arpit2126** [angular/angular-seed#263]
I have tried to use angular-seed but I am unable to install packages using npm. I am using node V0.12.1. I am able to install almost all the packages globally but when i m doing npm install it is showing timeout error. For more details look into the issue
![image](https://cloud.githubusercontent.com/assets/8288314/6914024/3a3878da-d7a4-11e4-8fc1-dac11ad0bf3a.png)

Things I tried:
changed the proxy it didn't work . 

Please suggest I want to use protractor with Jasmine or Karma with Jasmine in my angular project

**Comment by dc-deal** [comment]
here is the answer...
http://stackoverflow.com/questions/20666989/bower-enogit-git-is-not-installed-or-not-in-the-path

Quote
Run the following command at your node.js command prompt where "<git path>" is the path to your git bin folder:

set PATH=%PATH%;<git path>;
So, like this:

set PATH=%PATH%;C:\Program Files\Git\bin;
Or this: (Notice the (x86) )

set PATH=%PATH%;C:\Program Files (x86)\Git\bin;
This will add git to your path variables. Be sure you type it correctly or you could possibly delete your path vars which would be bad.

**Comment by gkalpak** [comment]
Since there hasn'e been any update in a while, I assume this is not an issue any more.
