### ISSUE TITLE
Npm install error unlock bower

### ISSUE THREAD

**Issue by pasx** [angular/angular-seed#266]
Here is what I get trying to install on Linux Mint  16 64bits
...
60 silly lockFile 7c83895e-bower-1-3-1 bower@^1.3.1
61 error Error: Attempt to unlock bower@^1.3.1, which hasn't been locked
61 error     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
61 error     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:32:5)
61 error     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:41:20
61 error     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:30:7
61 error     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
61 error     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
61 error     at Object.oncomplete (fs.js:107:15)
62 error If you need help, you may report this *entire* log,
62 error including the npm and node versions, at:
62 error     <http://github.com/npm/npm/issues>
63 error System Linux 3.11.0-12-generic
64 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install"

Just followed instructions on https://github.com/angular/angular-seed

And I know it is pretty dumb but just in case someone else runs into this, this sentence:

"We get the angular code via bower, a client-side code package manager"

Actually means: "Go ahead and install bower..."

**Comment by gkalpak** [comment]
Actually, you don't need to install `bower` manually (or globally).
It will be installed (locally) and run automatically, whenever you run `npm install`.

<sub>(Maybe things were different back then, when this issue was opened.)</sub>
