### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by samx** [angular/angular-seed#271]
I've been able to get this to work in the past. Recently tried to run npm install on an unedited angular-seed repo. But get errors and "node start" fails to initalize the server

-
> ws@0.4.32 install /Users/macbookpro/.Trash/angular-seed-master/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path /Users/macbookpro/.Trash/angular-seed-master/node_modules/karma/node_modules/chokidar/package.json
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, open '/Users/macbookpro/.Trash/angular-seed-master/node_modules/karma/node_modules/chokidar/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/macbookpro/.Trash/angular-seed-master/npm-debug.log

**Comment by angajime** [comment]
Same issue here... It looks like there is something wrong with pakage.json but it is passing on [jsonlint.com](http://jsonlint.com)

**Comment by gkalpak** [comment]
As stated in the error message above (and verified by @angajime):

> This is most likely not a problem with npm itself

--
Closing since this isn't related to `angular-seed`.
