### ISSUE TITLE
Error when run : npm run update-index-async

### ISSUE THREAD

**Issue by qianlong** [angular/angular-seed#272]
I've copied this project with git and ran :
>npm install
with successful

Then I ran :
>npm run update-index-async

and I've got an error:

![image](https://cloud.githubusercontent.com/assets/642415/7650096/5f95a0e0-faf3-11e4-8943-f2e2eebb567f.png)

**Comment by gkalpak** [comment]
Should have been fixed by #343.
(Please open a new issue, if you are still facing any problem.)
