### ISSUE TITLE
npm start not working on angular seed !

### ISSUE THREAD

**Issue by harshattray** [angular/angular-seed#275]
/AngularJSSTB/node_modules/.bin/bower: line 1: ../bower/bin/bower: No such file or directory

npm ERR! Darwin 14.1.1
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular-seed@0.0.0 postinstall: `bower install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/harsha/projects/workspace/myprojects/AngularJSSTB/npm-debug.log

**Comment by mrmayfield** [comment]
Getting the same error. Did you ever fix it?

**Comment by mrmayfield** [comment]
This fixed it for me 
```
$ git config --global url."https://".insteadOf git://
```

**Comment by mrmayfield** [comment]
@harshattray  did that fix the error for you?

**Comment by harshattray** [comment]
Yes it did .. thank you

**Comment by mrmayfield** [comment]
No problem! Want to follow me back on Github? :)
