### ISSUE TITLE
Uncaught Error: [$injector:modulerr]

### ISSUE THREAD

**Issue by skalekarr** [angular/angular-seed#276]
Hi,
I just created a new project in WEBSTORM using this angular-seed. When i tried to run it after installing all the dependencies, it is showing the fallowing error.

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.0/$injector/modulerr?p0=myApp&p1=Error%3A%2…lhost%3A63342%2FDemos%2Fnode_modules%2Fangular%2Fangular.min.js%3A19%3A264)

**Comment by gkalpak** [comment]
Closing as this is pretty old and also not actionable.
If anyone is still facing problems, please open a new issue providing the necessary details.
