### ISSUE TITLE
 error angular-seed@0.0.0 start: `http-server -a localhost -p 8000 -c-1`

### ISSUE THREAD

**Issue by CyanChoi** [angular/angular-seed#280]
when  npm install I met an error,
here is the log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.28
3 info using node@v0.10.34
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart angular-seed@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info start angular-seed@0.0.0
9 verbose unsafe-perm in lifecycle true
10 info angular-seed@0.0.0 Failed to exec start script
11 error angular-seed@0.0.0 start: `http-server -a localhost -p 8000 -c-1`
11 error Exit status 8
12 error Failed at the angular-seed@0.0.0 start script.
12 error This is most likely a problem with the angular-seed package,
12 error not with npm itself.
12 error Tell the author that this fails on your system:
12 error     http-server -a localhost -p 8000 -c-1
12 error You can get their info via:
12 error     npm owner ls angular-seed
12 error There is likely additional logging output above.
13 error System Windows_NT 6.2.9200
14 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error cwd D:\abc\angular-seed-master
16 error node -v v0.10.34
17 error npm -v 1.4.28
18 error code ELIFECYCLE
19 verbose exit [ 1, true ]

it seems the localhost 8000 is not avalilable, please can any body tell me how to fix it?

**Comment by balazsnemeth** [comment]
Do you have any update on it, I have the same issue, may you did solved it?

**Comment by vriestimo** [comment]
CyanChoi, have you tried running the app in multiple browsers?

When I tried running the angular seed app in Pale Moon, it threw the above error, but when I did the same in Chrome, it worked fine. I'm guessing it's a browser issue.

**Comment by shan31** [comment]
please can any body tell me how to fix it For me also have an same error

**Comment by Warlord08** [comment]
Have you check if the 8000 address is already in use by other server? (Mamp, wamp, etc)

**Comment by xjkms** [comment]
I have a similar problem,  any one fixed this problem yet?

**Comment by gkalpak** [comment]
All dependencies and tools have been updated recently and this is hopefully not an issue any more.
If anyone is still having problems, please open a new issue.
