### ISSUE TITLE
npm start causing "npm WARN cannot run in wd"

### ISSUE THREAD

**Issue by itsduc** [angular/angular-seed#291]
I tried this and it didn't work. 
> npm start --unsafe-perm

I keep getting this error. 

> bower ESUDO         Cannot be run with sudo
> You can however run a command with sudo using --allow-root option
> npm ERR! weird error 1
> npm ERR! not ok code 0
> npm ERR! weird error 1
> npm ERR! not ok code 0

Without --unsafe-perm I keep getting this error instead: 
> npm WARN cannot run in wd angular-seed@0.0.0 bower install (wd=/usr/share/nginx/angular-seed)

**Comment by SydOps** [comment]
i saw the same error, but seems the website start and is running well.

**Comment by shyamveerapally** [comment]
0

**Comment by paulvivier** [comment]
May be the same resolve as this issue:  https://github.com/angular/angular-seed/issues/227
Install bower separately with npm per final comment.

**Comment by gkalpak** [comment]
Closing as this is about a more general problem - not directly related to `angular-seed` itself.
