### ISSUE TITLE
The seed project is tremendously slow in production server(AWS M3.large)

### ISSUE THREAD

**Issue by prithvirajanm** [angular/angular-seed#299]
Very recently i've deployed a custom angular seed application in AWS m3.large instance which is too slow in fetching the responses/loading resources.(Monitored using firebug and it takes around 30 seconds to load the home page)

It seems to work fine in the local development environment. But no reason why this slow down happened. Is there any crucial things to do with angular seed for production?

The problem here is the loading of static files and asynchronous responses from server(Java Backed). They don't even size much. The total response size is 955kb including all static files and server responses.

My node version is 0.10.37. Any help is much appreciated.

**Comment by boykoc** [comment]
When you look at your network in developer tools is there a specific file that takes along time to load?

**Comment by prithvirajanm** [comment]
Hi Cody,

Thanks for replying. Yes it was too slow. Now, I'm serving all static 
files from nginx and it has reduced considerable load time. Now I could 
load the home page in 5-6 seconds.

**Comment by robertbaker** [comment]
@prithvirajanm that's still too slow, you need under 2 seconds. Maybe some of it is your web hosting provider. But TBH you are better off using the official cdn's for major frameworks and plugins. It would be faster than loading angular on your own server.

**Comment by prithvirajanm** [comment]
@Robert I'm running them in AWS m3 large instance with 7.5 gigs of RAM. For performance tuning, I've tried loading plugins from cdn and moved all the images to serve from S3 and reduced number of watchers in the angular code. So this is how now i'm able to get in 5 to 6 seconds. If still, this can be fine tuned, please point me to a direction. I'm just a java developer with no good at front end technologies. Should I start using yeoman like tools for compression?

**Comment by aleksandar-smiljanic** [comment]
Is your JS concatenated and minified?

**Comment by prithvirajanm** [comment]
@ Aleksandar Not yet, but which i'm considering to do next. For this I'm looking into grunt and yeoman.

**Comment by robertbaker** [comment]
@prithvirajanm Use gulp instead, Yeoman is a project scaffolding tool. It wouldn't be useful for an existing project unless you wanted to transplant your project into a seed.

Minify and Concatenate should be done.

After that, looking into AMD modules and a package manager & loader such as webpack or jspm, combined with angularAMD would be the next step.

**Comment by gkalpak** [comment]
Closing as this is a general support question.
