### ISSUE TITLE
ELIFECYCLE error

### ISSUE THREAD

**Issue by avorobyev** [angular/angular-seed#314]
Getting this error. Could you please share ideas how to fix it.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor',
1 verbose cli   '--',
1 verbose cli   '--env=dev',
1 verbose cli   '--browsers=firefox',
1 verbose cli   '--suite=full',
1 verbose cli   '--debug',
1 verbose cli   '--username=user',
1 verbose cli   '--password=password' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor SVB-Angular@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor SVB-Angular@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info SVB-Angular@0.0.0 Failed to exec protractor script
10 verbose stack Error: SVB-Angular@0.0.0 protractor: `gulp protractor "--env=dev" "--browsers=firefox" "--suite=full" "--debug" "--username=user" "--password=password"`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid SVB-Angular@0.0.0
12 verbose cwd C:\Integration_test_040new
13 error Windows_NT 6.1.7601
14 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor" "--" "--env=dev" "--browsers=firefox" "--suite=full" "--debug" "--username=user" "--password=password"
15 error node v0.12.7
16 error npm  v2.11.3
17 error code ELIFECYCLE
18 error SVB-Angular@0.0.0 protractor: `gulp protractor "--env=dev" "--browsers=firefox" "--suite=full" "--debug" "--username=user" "--password=password"`
18 error Exit status 1
19 error Failed at the SVB-Angular@0.0.0 protractor script 'gulp protractor "--env=dev" "--browsers=firefox" "--suite=full" "--debug" "--username=user" "--password=password"'.
19 error This is most likely a problem with the SVB-Angular package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     gulp protractor "--env=dev" "--browsers=firefox" "--suite=full" "--debug" "--username=user" "--password=password"
19 error You can get their info via:
19 error     npm owner ls SVB-Angular
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by rob-craven** [comment]
I'm receiving the same error, any suggestions?

**Comment by rob-craven** [comment]
Behind corporate firewall, need to update git.config so that npm can access github to pull down angular dependencies. Navigate to .git folder within your project directory, and edit the config file, add the below URL re-write command, and save file.

`[url "https://github.com/"]
    insteadOf = "git://github.com/"`

Note, you may also need to install Git globally, by ensuring you select the option to run Git globally from command prompt.

**Comment by gkalpak** [comment]
Since there was no response form the OP, I assume this is not an issue any more.
