### ISSUE TITLE
Call scripts inside Angular Seed

### ISSUE THREAD

**Issue by fillocj** [angular/angular-seed#319]
There some links I'd like to add in angular-seed such datePicker or google charts but it simply seems doesn't recognize the script links. 
How can I call them in a a view1 for example? 
Thanks in advance.

**Comment by gkalpak** [comment]
It is not clear what the problem is. What do you mean by _"it simply doesn't recognize the script links"_?

**Comment by gkalpak** [comment]
Since there was no response from the OP, I assume this is no longer an issue. Closing.
