### ISSUE TITLE
Access error when I give the npm install -g bower command on mac

### ISSUE THREAD

**Issue by rus-techie** [angular/angular-seed#320]
I am getting the following error when I give the "npm install -g bower" command. And then later when I give a command like "bower install bootstrap" it gives a message "command not found". I have installed latest version of node.js with which bower would have been installed. Please suggest.

"
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└── bower@1.7.7 

npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
"

Thanks.

**Comment by edisanto** [comment]
did you try as administrator? (sudo npm install -g bower)

**Comment by rus-techie** [comment]
Thanks a lot. 
It did work and created the required bootstrap files in bower_components.

But still, I get the following error on running "npm install". Do I need to uninstall node.js  and then install all the components again, or is it some other issue. 

npm install

> bufferutil@1.2.1 install /Users/Sachin/Ruchika_Projects/templateStore/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Sachin/Ruchika_Projects/templateStore/node_modules/bufferutil
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install /Users/Sachin/Ruchika_Projects/templateStore/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/validation.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Sachin/Ruchika_Projects/templateStore/node_modules/utf-8-validate
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1

> angular-seed@0.0.0 postinstall /Users/Sachin/Ruchika_Projects/templateStore
> bower install

**Comment by mgol** [comment]
@rus-techie Did you install XCode Command Line Tools? You can hardly do anything programming-related without them installed on a Mac.

**Comment by rus-techie** [comment]
Yes, I have XCode installed on my Mac. Still it gives the above error.

**Comment by gkalpak** [comment]
I'm going to close this, since it isn't directly related to `angular-seed`. Installing node modules globally (either with or without sudo) is a big topic, but not related to this project.
(BTW, note that it is not strictly necessary to install `bower` globally for `angular-seed`.)

**Comment by abhishekpr9** [comment]
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "gulp" "-g"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! path /home/abhishek/.npm-global/lib/node_modules/gulp
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/home/abhishek/.npm-global/lib/node_modules/gulp'
npm ERR!  { Error: EACCES: permission denied, access '/home/abhishek/.npm-global/lib/node_modules/gulp'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/abhishek/.npm-global/lib/node_modules/gulp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/abhishek/mywork/zykrr/rating/npm-debug.log


I am getting this error on running gulp on my ubuntu machine

**Comment by abhishekpr9** [comment]
can i get any solution for this

**Comment by gkalpak** [comment]
This is not related to this repo (`angular-seed`) does not use gulp.
For general support question suhc as this one, please use one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
