### ISSUE TITLE
npm install failure on a mac

### ISSUE THREAD

**Issue by rumpoint** [angular/angular-seed#325]
I've gone crazy trying to install dependencies via npm install but keep getting various errors. Any help appreciated. Here is my npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose config Skipping project config: /Users/bobwerber/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart angular-seed@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info angular-seed@0.0.0 Failed to exec prestart script
9 verbose stack Error: angular-seed@0.0.0 prestart: `npm install`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid angular-seed@0.0.0
11 verbose cwd /Users/bobwerber
12 error Darwin 14.3.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.0
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error angular-seed@0.0.0 prestart: `npm install`
17 error Exit status 1
18 error Failed at the angular-seed@0.0.0 prestart script 'npm install'.
18 error This is most likely a problem with the angular-seed package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm install
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs angular-seed
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls angular-seed
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by sidgujrathi** [comment]
It seems your nodeJS has problem, Please update or reinstall nodejs and try again. You can update nodejs by command `sudo npminstall -g n` and after updating nodejs update npm by typing `npm install -g npm`

**Comment by luiscamposjr** [comment]
Are you using "sudo"?

**Comment by waxmihs2902** [comment]
yes

**Comment by gkalpak** [comment]
Since there was no response from the OP, I assume this is not an issue any more.
