### ISSUE TITLE
Updating Angular Version 

### ISSUE THREAD

**Issue by mkoller** [angular/angular-seed#327]
What is he best practice to update the angular version? I see that angular get installed via bower when  `npm install` is run. This current repo uses AngularJS v1.4.1 but the latest release is 1.5.2 . 

Would I run `bower update angular --save-dev` ? Will that auto update my bower.json dependencies or will I manually have to change angular-route, angular-loader, angular-mocks and any additional angular dependencies to use 1.5.2 ?

**Comment by zhoubihn** [comment]
@mkoller  "You can update the tool dependencies by running:
npm update
This will find the latest versions that match the version ranges specified in the package.json file.
You can update the Angular dependencies by running:
bower update
This will find the latest versions that match the version ranges specified in the bower.json file."
