### ISSUE TITLE
Unable to install npm in windows 7

### ISSUE THREAD

**Issue by sahdev0** [angular/angular-seed#330]
Please find attached zip file

**Comment by zhoubihn** [comment]
First of all, you should install Node.js,please go to http://git-scm.com for downloading and installing Node for Windows.

**Comment by sidgujrathi** [comment]
To download and install node js, the link is [https://nodejs.org/en/download/](https://nodejs.org/en/download/)

**Comment by gkalpak** [comment]
Closing since this is not related to `angular-seed`.
