### ISSUE TITLE
ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by zhoubhin** [angular/angular-seed#332]
Wneh i access http://localhost:8000/app/index.html, browser say "Link have been reset".Windows 10 with Chrome, Node v4.3.0

**Comment by debadeep75** [comment]
The solution is very simple, check out this awesome guide on [](http://highpuf.com/2016/05/26/err-connection-reset/) for more information.

**Comment by zhoubhin** [comment]
@debadeep75  thanks, I've solved this problem
