### ISSUE TITLE
chore: update the codebase (e.g. directory layout, file naming etc)

### ISSUE THREAD

**Issue by gkalpak** [angular/angular-seed#334]
Once/If #341 is merged, it would be a good idea to update the code organization to adhere to latest _best practices&trade;_ and bring the seed closer to the tutorial (see angular/angular-phonecat#326). E.g.:
- [x] Rename `components/` to `core/` or `common/`.
    Now that "components" means something different, it can be confusing.
- [x] Rename `_test.js` files to `.spec.js`.
- [ ] Rename module definitions files to `.module.js`.
- [x] Update `karma.conf.js` to account for the above changes.
- [ ] Optionally, use components when appropriate.

**Comment by gkalpak** [comment]
Some of the points above will be addressed in #444.
We won't be making more changes now that AngularJS is in [LTS mode][1].

[1]: https://docs.angularjs.org/misc/version-support-status

**Comment by petebacondarwin** [comment]
Core makes it sound like it is part of AngularJS no? I could live with common or shared

**Comment by gkalpak** [comment]
I personally prefer `shared` as well, but I tried to lousely follow the Angular style guide. It suggests having a [shared directory/module][1] and a [core directory/module][2].
I felt that the type of things we had in `components/` was better suited for `core/` (but happy to move to `shared/` instead).

[1]: https://angular.io/guide/styleguide#shared-feature-module
[2]: https://angular.io/guide/styleguide#core-feature-module
