### ISSUE TITLE
Incorrect Syntax : git clone --depth=1 https://github.com/angular/angular-seed.git <your-project-name>

### ISSUE THREAD

**Issue by selvaonline** [angular/angular-seed#335]
I have used the below command as per documentation and it is still carry on the history

`git clone --depth=1 https://github.com/angular/angular-seed.git <your-project-name>`

I am running git 2.6.3 for windows and git bash shell. its look like --depth=1 syntax is wrong and it should be like --depth 1. Could you please correct the syntax in the documentation?

**Comment by Amarian** [comment]
git clone --depth 1 

this might do the trick?

**Comment by selvaonline** [comment]
yes. please correct the documentation in github.

**Comment by gkalpak** [comment]
I am pretty sure it works both ways.
