### ISSUE TITLE
when executing the test as "npm run e2e:local" getting error, please below complete logs

### ISSUE THREAD

**Issue by abidrana7** [angular/angular-seed#337]
D:\emiral>npm run e2e:local

> emiral@0.13.9-3 e2e:local D:\emiral
> ./node_modules/protractor/bin/webdriver-manager update && ./node_modules/.bin/
protractor .cicd/protractor.conf.js

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e:local"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! emiral@0.13.9-3 e2e:local: `./node_modules/protractor/bin/webdriver-man
ager update && ./node_modules/.bin/protractor .cicd/protractor.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the emiral@0.13.9-3 e2e:local script './node_modules/protract
or/bin/webdriver-manager update && ./node_modules/.bin/protractor .cicd/protract
or.conf.js'.
npm ERR! This is most likely a problem with the emiral package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/protractor/bin/webdriver-manager update && ./node_mo
dules/.bin/protractor .cicd/protractor.conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls emiral
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\emiral\npm-debug.log

**Comment by gkalpak** [comment]
This doesn't seem to be related to `angular-seed`. It is also impossible to help further without more info (there is no `e2e:local` script in `angular-seed`, so no idea where this came from).

Closing as non-actionable. Please open a new issue, providing all the necessary details, if you are still facing problems.
