### ISSUE TITLE
Is there an easy grunt file template for this somewhere?

### ISSUE THREAD

**Issue by nkiermaier** [angular/angular-seed#345]
Not trying to be picky. This is a great resource.  
It would be nice to be able to have a quick and easy grunt file to plug in, like a template for grunt-init or something to get grunt going out the box without have to write a grunt.js file.

**Comment by gkalpak** [comment]
I think providing templates for all possible task-runners is outside of the scope of this project. This is a basic starting point and should be as unopinionated as possible as far as specific tooling is concerned.

There are already npm scripts for the core tasks (such as starting a local server, running unit and e2e tests etc). If you want to use a task runner on top (grunt, gulp, brocolli, ???), you should provide the configuration file yourself imo.

**Comment by nkiermaier** [comment]
:( understood.  It makes sense.  I'll just make one myself! With blackjack and hookers!
In all seriousness this an awesome resource, thanks much for ya'lls work on this.
