### ISSUE TITLE
Angular seed with Bootstrap

### ISSUE THREAD

**Issue by bevankoopman** [angular/angular-seed#346]
Thanks for creating this project. Would it be possible to have a basic project that uses bootstrap formatting? Thanks.

**Comment by gkalpak** [comment]
This project tries to stay as unopinionated as possible (as far as non-Angular stuff is concerned), so bringing in a specific UI framework is outside the scope of angular-seed.

There are lots of other (more opinionated) seed projects though; I wouldn't be surprised if some of them included Bootstrap :wink:
