### ISSUE TITLE
chore: fix the CI job

### ISSUE THREAD

**Issue by gkalpak** [angular/angular-seed#347]
Currently, the [CI job][1] is failing (probably due to an outdated build script. The script that is executed by Jenkins does the following:

1. Remove the `test_out/` directory (`rm -rf test_out`).
2. Install npm dependencies (`npm install .`).
3. Run unit tests (`./scripts/test.sh --single-run --browsers="$BROWSERS" ...`).
4. Run e2e tests (`./scripts/web-server.js ... ./scripts/e2e-test.sh --single-run --browsers="$BROWSERS" ...`).

<sub>Where: BROWSERS="Chrome,Firefox,Opera,/Users/jenkins/bin/safari.sh,/Users/jenkins/bin/ie8.sh,/Users/jenkins/bin/ie9.sh"</sub>

--
A revised `build-angular-seed.sh` script could be:

```bash
#!/bin/bash

set -ex

# Switch to Node.js v4.4.x
source ~/.nvm/nvm.sh
nvm install 4.4

# Shut down the web-server when done
cleanUp () {
  kill $WEBSERVER_PID
}
trap cleanUp EXIT

# Install npm dependencies and the ChromeDriver
npm install
npm run update-webdriver

# Start the web-server
node_modules/.bin/http-server ./app -a localhost -p 8000 -c-1 --silent & WEBSERVER_PID=$!

# Run the tests
node_modules/.bin/karma start karma.conf.js --single-run
node_modules/.bin/protractor e2e-tests/protractor.conf.js --directConnect
```
<sub>(This is very similar to what we use in `angular-phonecat`'s [test-all.sh][2].)</sub>

We would no longer need any script under `scripts/`.
The difference would be that the e2e tests would be run against Chrome only (but I think it is OK for the needs of this project).

[1]: https://ci.angularjs.org/job/angular-seed-master/
[2]: https://github.com/angular/angular-phonecat/blob/2ccda1d7075ba0f3900ddf1a107c8e9b6942767f/scripts/private/test-all.sh

**Comment by gkalpak** [comment]
BTW, we also make sure that the currently used scripts don't have some extra "feature" that we are missing.

**Comment by gkalpak** [comment]
Updated the script to also use `nvm` + Node.js v4.4.x .

**Comment by petebacondarwin** [comment]
This seems to be fixed now - we updated the CI server with the script from this issue.
Thanks @gkalpak
