### ISSUE TITLE
Issue with running protractor tests on Jenkins

### ISSUE THREAD

**Issue by clipsett** [angular/angular-seed#349]
I have a job set up on Jenkins that runs http-server to server up my angularjs files, and then another process to run my protractor tests. 

If I run http-server and protractor <conf.js> on my local machine, my tests run and pass as expected, when I get to Jenkins, I get the following output:

[15:04:26] I/local - Starting selenium standalone server...
[15:04:26] I/launcher - Running 1 instances of WebDriver
[15:04:29] I/local - Selenium standalone server started at http://10.1.1.82:59698/wd/hub
[15:04:29] E/launcher - "process.on('uncaughtException'" error, see launcher
[15:04:29] E/launcher - Process exited with error code 199

This happens after calling protractor from a Jenkins VM.

The interesting thing I've found is that, if I run the tests locally, without starting webdriver-manager, the tests pass. If I run webdriver-manager, the tests fail with the same error as above. I'm not sure what's going on with my Jenkins build currently, but it appears webdriver-manager may be contributing. 

I haven't been able to get the protractor tests to pass on Jenkins yet as they always fail after I call protractor. I can provide my conf.js if necessary, however it is very simple.

**Comment by bhavicool** [comment]
@clipsett : Even I am facing same issue, why have you closed it?

**Comment by clipsett** [comment]
@bhavicool I can't remember why I closed the issue, but I do know we decided not to use Jenkins to run the protractor tests.

**Comment by bhavicool** [comment]
@clipsett: Ok.. Actually I was facing same issue today scripts were passing in my ide (vsc) but failing in Jenkins.. pls let me know if you have any idea abt it...
