### ISSUE TITLE
better webpack implementation

### ISSUE THREAD

**Issue by istiti** [angular/angular-seed#350]
this include webpack, it's very nice

but when I did npm run build all my .js files go to /dist ... but there are no index.html and css style in separated file. Will someone implements that ?

**Comment by gkalpak** [comment]
Are you sure this is the right repo? We don't provide a `build` npm script (nor do we include webpack).

If you are requesting that we add webpack to the project, I don't think it would be a good fit. This project is a basic starting point and should stay as unopinionated as possible (wrt non-Angular stuff). So, bringing in a specific built tool is outside the scope of angular-seed.
