### ISSUE TITLE
Hi, after cloning out of the box, it flickers between the view and the directive

### ISSUE THREAD

**Issue by edfimasa** [angular/angular-seed#352]
Hi, I'm new with Angular, and I have to learn and use version 1.

I've cloned using this
git clone --depth=1 https://github.com/angular/angular-seed.git <your-project-name>

after starting the app, I noticed the version showing before the view1. And pressing f5 it shows it again and again the flicker.

even using ng-cloak, even using the css trick (!important) it improves it, but if I press F5 enough times it some times shows the version before the view in a split of a second.

Can you help on this?

Thanks,
Edgar

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by edfimasa** [comment]
I would call it a bug. So it's in the right place.

**Comment by gkalpak** [comment]
It is not a bug. It is expected behavior.

In a nutshell:
Routes are loaded asynchronously (especially in this basic app the templates are fetched from the server which introduces extra latency), so it is expected that other (less dynamic) parts of the page are visible before a route has been loaded.

**Comment by edfimasa** [comment]
Thanks, but ng-cloak should do the trick and it doesn't.

**Comment by edfimasa** [comment]
But ok, thanks, I found a way around it. by using  angular-csp.css
