### ISSUE TITLE
Need to load template/templateUrl dynamically

### ISSUE THREAD

**Issue by ravindra1436** [angular/angular-seed#353]
Hi,
I want to load template dynamically. like below,

@Component({
selector:'my-app',
templateUrl: GetTemplate()
})

or

@Component({
selector:'my-app',
template: GetTemplateHtml()
})

export class MyAppComponent{

GetTemplateHtml(){
    return './app.component.html' // This will fetch drom services.
}
}

Some thing like that.
Please help
Thanks in advance

**Comment by gkalpak** [comment]
This repo is for `angular-seed`, a basic seed project for Angular 1. Your code looks like Angular 2 and your question like a general support question.

You should use one of the [general support channels][1] for there types of questions.
In any case, the Angular 2 repo is [here][2].

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[2]: https://github.com/angular/angular
