### ISSUE TITLE
Error with npm start

### ISSUE THREAD

**Issue by akhilkooliyatt** [angular/angular-seed#354]
On npm start I get the following error. Is this a node setup issue? Any help is appreciated.
> http-server -a localhost -p 8000 -c-1 ./app

Error: EINVAL, invalid argument
    at new Socket (net.js:156:18)
    at process.stdin (node.js:664:19)
    at Object.<anonymous> (F:\0-TUTS\AngularJS 2 Essential Training\Angular- Learn with 10 example\AngularWeekend\templatestore\node_modules\http-server\bin\http-server:159:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! angular-seed@0.0.0 start: `http-server -a localhost -p 8000 -c-1 ./app`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 start script.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a localhost -p 8000 -c-1 ./app
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej                                                                                                                s\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd F:\0-TUTS\AngularJS 2 Essential Training\Angular- Learn with 10 exa                                                                                                                mple\AngularWeekend\templatestore
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm

**Comment by gkalpak** [comment]
I've never seen that one before. What version of Node are you using?

**Comment by akhilkooliyatt** [comment]
The issue is fixed. I was running `npm start` from git bash. Ran the same command from command prompt and is working fine. Not sure why it wasn't working while running from git bash. I even tried running it as administrator.

**Comment by gkalpak** [comment]
No idea why it didn't work, but glad to hear you sorted it out :smile:
