### ISSUE TITLE
Bower Install Fails on the system

### ISSUE THREAD

**Issue by nayan576** [angular/angular-seed#359]
(wye) nayan@ubuntu:~/Desktop/wye/angular-seed(master)$ npm install
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> angular-seed@0.0.0 postinstall /home/nayan/Desktop/wye/angular-seed
> bower install

/usr/bin/env: ‘node’: No such file or directory

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular-seed@0.0.0 postinstall: `bower install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nayan/Desktop/wye/angular-seed/npm-debug.log

[npm-debug.log.zip](https://github.com/angular/angular-seed/files/436646/npm-debug.log.zip)

**Comment by gkalpak** [comment]
`npm install` seems to be failing (based on the attached `npm-debug.log`). Could it be a permissions issue? What is the output if you run `npm install` directly?

**Comment by iAyush** [comment]
I am having the same issue..does it have anything to do with Windows10..?

**Comment by gkalpak** [comment]
It works fine on Windows 10 for me :confused:

**Comment by faddat** [comment]
Same issue, here are the details:

```
[faddat@arch-anywhere]: ~/gocryptotrader/web>$ npm start

> angular-seed@0.0.0 prestart /home/faddat/gocryptotrader/web
> npm install


> angular-seed@0.0.0 postinstall /home/faddat/gocryptotrader/web
> bower install

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

> angular-seed@0.0.0 start /home/faddat/gocryptotrader/web
> node server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1240:19)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/home/faddat/gocryptotrader/web/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/faddat/gocryptotrader/web/server.js:32:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

npm ERR! Linux 4.7.2-1-ARCH
npm ERR! argv "/home/faddat/.nvm/versions/node/v6.4.0/bin/node" "/home/faddat/.nvm/versions/node/v6.4.0/bin/npm" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/faddat/gocryptotrader/web/npm-debug.log
[faddat@arch-anywhere]: ~/gocryptotrader/web>$ node server.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1240:19)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/home/faddat/gocryptotrader/web/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/faddat/gocryptotrader/web/server.js:32:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

I think it may be my version of node?  I'm going to dial it back one in nvm and will let you know.

**Comment by gkalpak** [comment]
@faddat, yurs is a different error. It means that the address/port combination is in use, so the werver that is trying to bind to that port fails.

I also see in your logs that node is trying to execute `server.js`, which does not exist in this repo. Your problem is not related to angular-seed actually.

**Comment by faddat** [comment]
oh, well then!  Thank you very much @gkalpak 🎯 

I should have spotted that, but will remember that's what it "looks like" in the future.

**Comment by amitsng7** [comment]
Getting this error. Please help me if anyone have any idea.

bower html5-boilerplate#^5.3.0  ENOGIT git is not installed or not in the PATH

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by gkalpak** [comment]
Closing since we didn't get any feedback from the OP.
