### ISSUE TITLE
Restoring packages holds forever after "npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14"

### ISSUE THREAD

**Issue by LightRay2** [angular/angular-seed#362]
I follow Visual Studio 2015 quickstart turorial. (https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html).

When I do Step 5: Restore the required packages, according to tutorial, after some time I should see : "npm command completed with exit code 0".
But restoring packages holds in the middle of the process. In output I see the last lines :
...
...
| | |   +-- registry-url@3.1.0 
| | |   `-- semver@5.3.0 
| | +-- lazy-req@1.1.0 
| | +-- semver-diff@2.1.0 
| | | `-- semver@5.3.0 
| | `-- xdg-basedir@2.0.0 
| |   `-- os-homedir@1.0.1 
| +-- wordwrap@1.0.0 
| `-- xtend@4.0.1 
`-- zone.js@0.6.17 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

After this there was no progress for an hour ( I tried it several times with clearing cache before).
What can I do with it? (I have windows 10 x64, if it's important)

**Comment by gkalpak** [comment]
Your problem is not related to this repo. This seed project is for angular 1.
I would try asking on one of the general support channels (e.g. StackOverflow, Gitter etc).
