### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by amitsng7** [angular/angular-seed#365]
Not able to install npm. Please help
 npm install

npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! not a package C:\Users\Amit Singh\AppData\Roaming\npm-cache\fill-range\2.2.3\package.tgz
npm ERR! not a package C:\Users\Amit Singh\AppData\Roaming\npm-cache\agent-base\2.0.1\package.tgz
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! file C:\Users\Amit Singh\AppData\Roaming\npm-cache\minimatch\0.3.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\Amit Singh\AppData\Roaming\npm-cache\minimatch\0.3.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Amit Singh\Desktop\Project\tracxpense\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 prestart: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 prestart script 'npm install'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

**Comment by gkalpak** [comment]
It seems that you npm cache (`C:\Users\Amit Singh\AppData\Roaming\npm-cache`) is corrupted.
Try cleaning the cache (e.g. `npm cache clean`).

In any case, this is not an issue with `angular-seed` itself.
