### ISSUE TITLE
How to debug Gulp tasks written in TypeScript with WebStorm ?

### ISSUE THREAD

**Issue by hivaga** [angular/angular-seed#366]
Well I am using the seed for some time now and I can't figure out how we can add break point and debug Gulp task written in TypeScript. I am using WebStrom but if someone can do it with other IDE it is also good. The problem is that we have gulpfile.ts and other TypeScript Gulp tasks which are  executed  the same way as JavaScript written gulp tasks but obviously a lot is happening behind the scene and there is no info what exactly. Here for example how I run a TypeScript gulp task "gulp build.js.dev" it runs just fine but when you try to debug it via WebStorm that is what happens:

"C:\Program Files (x86)\JetBrains\WebStorm 2016.2.3\bin\runnerw.exe" "C:\Program Files (x86)\nodejs\node.exe" --debug-brk=52284 --expose_debug_as=v8debug "E:\XXX\node_modules\gulp\bin\gulp.js" --color --gulpfile "E:\XXX\gulpfile.ts" build.js.dev
Debugger listening on [::]:52284
[21:48:27] Requiring external module ts-node/register

Process finished with exit code -1073741510 (0xC000013A: interrupted by Ctrl+C)

Can someone explain why this is happening and how to fix it? and in general how the TypeScript Gulp tasks are able to be compiled to js and passed behind the scene to Gulp Node Module.

**Comment by gkalpak** [comment]
This does not seem related to this seed project (maybe you are using another with a similar name).
This one is about AngularJS and does not use gulp or TypeScript.

**Comment by hivaga** [comment]
Yes, my mistake sorry.
