### ISSUE TITLE
npm start issue 

### ISSUE THREAD

**Issue by hms15** [angular/angular-seed#368]
> angular-seed@0.0.0 start C:\Users\hsewak\Desktop\MyFirstApp
> http-server -a localhost -p 8000 -c-1 ./app

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:83:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                                  node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 start: `http-server -a localhost -p 8000 -c-1 ./app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 start script 'http-server -a localhost                                                                                                                                   -p 8000 -c-1 ./app'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a localhost -p 8000 -c-1 ./app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hsewak\Desktop\MyFirstApp\npm-debug.log

**Comment by gkalpak** [comment]
The `EADDRINUSE` error means that the port (8000) is already in use by some other app/server.
Make sure that the port is not in use, before starting the local server.

<sub>(Alternatively, you could specify a different port, but it is slightly more involved.)</sub>
