### ISSUE TITLE
setup-protractor

### ISSUE THREAD

**Issue by shasha123456** [angular/angular-seed#372]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\shasha\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'setup-protractor' ]
2 info using npm@3.8.8
3 info using node@v4.5.0
4 verbose run-script [ 'presetup-protractor',
4 verbose run-script   'setup-protractor',
4 verbose run-script   'postsetup-protractor' ]
5 info lifecycle angular-seed@1.2.0-rc-2~presetup-protractor: angular-seed@1.2.0-rc-2
6 silly lifecycle angular-seed@1.2.0-rc-2~presetup-protractor: no script for presetup-protractor, continuing
7 info lifecycle angular-seed@1.2.0-rc-2~setup-protractor: angular-seed@1.2.0-rc-2
8 verbose lifecycle angular-seed@1.2.0-rc-2~setup-protractor: unsafe-perm in lifecycle true
9 verbose lifecycle angular-seed@1.2.0-rc-2~setup-protractor: PATH: C:\Users\shasha\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\shasha\Desktop\1234\my-project\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;D:\oracle\product\10.2.0\db_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Java\jdk1.8.0_65\bin;C:\Program Files\MySQL\MySQL Server 5.1\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\bin;C:\Python34;D:\apache-maven-3.3.9\bin;C:\Program Files\Redis\;C:\Program Files\nodejs\;C:\Users\shasha\AppData\Roaming\npm
10 verbose lifecycle angular-seed@1.2.0-rc-2~setup-protractor: CWD: C:\Users\shasha\Desktop\1234\my-project
11 silly lifecycle angular-seed@1.2.0-rc-2~setup-protractor: Args: [ '/d /s /c', 'grunt webdriver:update' ]
12 silly lifecycle angular-seed@1.2.0-rc-2~setup-protractor: Returned: code: 3  signal: null
13 info lifecycle angular-seed@1.2.0-rc-2~setup-protractor: Failed to exec setup-protractor script
14 verbose stack Error: angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
14 verbose stack Exit status 3
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\shasha\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:244:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\shasha\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular-seed@1.2.0-rc-2
16 verbose cwd C:\Users\shasha\Desktop\1234\my-project
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shasha\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "setup-protractor"
19 error node v4.5.0
20 error npm  v3.8.8
21 error code ELIFECYCLE
22 error angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
22 error Exit status 3
23 error Failed at the angular-seed@1.2.0-rc-2 setup-protractor script 'grunt webdriver:update'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     grunt webdriver:update
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-seed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by gkalpak** [comment]
This error message doesn't seem related to this repo. (For example, we don't use `grunt` and our version is 0.0.0, not 1.2.0-rc-2.)
