### ISSUE TITLE
Getting this issue Please help..

### ISSUE THREAD

**Issue by amitgaur208** [angular/angular-seed#374]
![capture](https://cloud.githubusercontent.com/assets/20765973/18956978/042784c0-867b-11e6-8d18-aaae6ea7471c.PNG)

![capture1](https://cloud.githubusercontent.com/assets/20765973/18957018/2c69ab02-867b-11e6-8286-6b47a8b69aae.PNG)
I have added angular.ja and route file but still i am getting the issue.
I have written this code

  $script([
      'angular.js',
      'angular-route.min.js',
      'app.js',
      'view1/view1.js',
      'view2/view2.js',
      'components/version/version.js',
      'components/version/version-directive.js',
      'components/version/interpolate-filter.js'
    ], function() {
      // when all is done, execute bootstrap angular application
      angular.bootstrap(document, ['myApp']);
    });

**Comment by gkalpak** [comment]
This seems like a minification problem. Some files are minified and the `angular

This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
