### ISSUE TITLE
How to install or add angular package into the app

### ISSUE THREAD

**Issue by noprobz09** [angular/angular-seed#375]
Hello,

I am newbie here, I would like to ask on how to add package something like this, https://github.com/likeastore/ngDialog#ngdialog, I tried to `npm install ng-dialog` but it appears outside app/ directory and it shows under node_modules directory, is that right? or is there any better steps on how to add package into the app? Thanks in advance :)

~Noel

**Comment by gkalpak** [comment]
Hi, @noprobz09. Since this is a general support question, please use one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
