### ISSUE TITLE
Getting issue when I activate html5 mode on

### ISSUE THREAD

**Issue by reachtokish** [angular/angular-seed#380]
Hi, I'm getting an issue for routing when I activate the html5 mode on. 

Can you please tell me process for the html5 mode on?

Thanks

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
