### ISSUE TITLE
" E/launcher - Process exited with error code 199" error am getting when tried to run the protractor

### ISSUE THREAD

**Issue by iamsarav** [angular/angular-seed#381]
I am a new Protractor.

1.  my conf.js file has : 
`exports.config = {
  seleniumAddress: 'http://localhost:3000/login',
  specs: ['todo-spec.js'],
  capabilities: {
    'browserName': 'chrome',
    chromeOnly:true ,
    directConnect: true
  }
};`

2.my 'todo-spec.js' file has : 

```
describe('Authentication capabilities', function() {
  var email = element(by.id('inputusername'));
  var password = element(by.id('inputPassword'));
  var loginButton = element(by.class('btn-success'));
 

it('should redirect to the login page if trying to load protected page while not authenticated', function() {
    browser.get('http://localhost:3000/login');
    loginURL = browser.getCurrentUrl();
    email.sendKeys("demo");
    password.sendKeys("demo");
    loginButton.click();
    
  });  
 });

```

but when i try to run the protractor by the following command "protractor "filepath\conf.js",
Im getting **" E/launcher - Process exited with error code 199"** error.

can anyone please let me know, where I'm doing mistake?

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

--
That said, a similar error was thrown when using Chrome v54 with older version of the ChromeDriver/Protractor (see https://github.com/angular/angular-cli/issues/2176#issuecomment-253496181). It shouldn't happen with Protractor v4.0.9+ though (which is what `angular-phonecat` is using), so not sure if it is related.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
