### ISSUE TITLE
Error with npm nam install: verbose stack Error: Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by FlyRicardo** [angular/angular-seed#388]
Hi, guys.

Look, I've tried to use the angular-seed as an application skeleton, but after cloned repository, when I run the `npm install`, I got this error on `npm-debug.log`:

- 0 info it worked if it ends with ok
- 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
- 2 info using npm@3.10.9
- 3 info using node@v7.2.0
- 4 verbose stack Error: Cannot find module 'internal/fs'
- 4 verbose stack     at Function.Module._resolveFilename (module.js:470:15)
- 4 verbose stack     at Function.Module._load (module.js:418:25)
- 4 verbose stack     at Module.require (module.js:498:17)
- 4 verbose stack     at require (internal/module.js:20:19)
- 4 verbose stack     at evalmachine.<anonymous>:17:20
- 4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
- 4 verbose stack     at Module._compile (module.js:571:32)
- 4 verbose stack     at Object.Module._extensions..js (module.js:580:10)
- 4 verbose stack     at Module.load (module.js:488:32)
- 4 verbose stack     at tryModuleLoad (module.js:447:12)
- 5 verbose cwd /Applications/XAMPP/xamppfiles/htdocs/angular-seed
- 6 error Darwin 15.6.0
- 7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
- 8 error node v7.2.0
- 9 error nam  v3.10.9
- 10 error code MODULE_NOT_FOUND
- 11 error Cannot find module 'internal/fs'
- 12 error If you need help, you may report this error at:
- 12 error     <https://github.com/npm/npm/issues>
- 13 verbose exit [ 1, true ]

, I'll be aware of your responses.

**Comment by FlyRicardo** [comment]
Hi, guys.

I've solved the problem by uninstalling _node_ and _node_modules_ from `/usr/local/lib/node_modules` and `/usr/local/include/node`, and then reinstalling _node_ via *brew*.

**Comment by gkalpak** [comment]
Yeah, it sounds like a vetsion mismatch of some sort - not related to angular-seed. Thx for the update. Closing...
