### ISSUE TITLE
Import bower components

### ISSUE THREAD

**Issue by ducmaxime** [angular/angular-seed#398]
Hi,

I try to import some bower components in my index.html (https://vaadin.com/docs/-/part/elements/angular2-polymer/overview.html)

1.   <script src="bower_components/webcomponentsjs/webcomponents.min.js"></script>

But I have 404 not found any idea ?

Thx

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
