### ISSUE TITLE
Use with elasticsearch

### ISSUE THREAD

**Issue by sxmon** [angular/angular-seed#399]
Hello,

I am new to Angular, and I am glad to see this seed.

I cloned it and made it work easily. Now I would like to open a connection with ElasticSearch. I tried to install elasticsearch and @types/elasticsearch but I get the following error : 

`http://localhost:5555/node_modules/elasticsearch.js Failed to load resource: the server responded with a status of 404 (Not Found)`

I added the following to app.component.ts : 

`import { Client, SearchResponse } from "elasticsearch";`

`private _client: Client;`

And in the constructor : 
`  
        if (!this._client) this._connect();
` 
 `  
    private _connect() {
        this._client = new Client({
            host: 'http://localhost:9200',
            log: 'trace'
        });
`

Thank you for helping me with angular-seed,

Simon

**Comment by gkalpak** [comment]
This is probably the wrong repo. Looking for https://github.com/mgechev/angular-seed?
