### ISSUE TITLE
How to create a barrel out of NPM packages in angular seed?

### ISSUE THREAD

**Issue by nechita** [angular/angular-seed#401]
Hi, I've looked through the closed issues, but I didn't find anything similar to what I'm experiencing.

I've added a few NPM packages to my angular project, and was trying to create a [barrel](https://angular.io/docs/ts/latest/glossary.html#!#barrel) out of the imports, to easily reference them without polluting the app.module.ts file.

I've created a folder called _kendo_ and created an index.ts file in which I've added my export statements, referencing the NPM packages I need to include in the barrel.

After the angular app is compiled again, I'm getting a 404 because it's looking for a kendo.js file, which it doesn't exist.

Do I need to add an alias or something, or what is the proper way of creating barrels out of NPM packages and referencing them in the app?

PS: this is the first issue I'm submitting to Github ever, so let me know if you need extra info to make my issue clearer.

**Comment by gkalpak** [comment]
This seed is for AngularJS (aka 1.x), not Angular (aka 2+). You are probably looking for a different seed project.
