### ISSUE TITLE
npm start fails on gupl serv.dev --color

### ISSUE THREAD

**Issue by toebes** [angular/angular-seed#403]
I'm trying to get a basic install running on Windows 10.  I just installed npm and node.js and even gulp to make sure I have the latest to no avail.

[npm-start-debug.txt](https://github.com/angular/angular-seed/files/842914/npm-start-debug.txt)

**Comment by gkalpak** [comment]
This is probably the wrong seed repo. This project does not use `gulp` in the first place.

**Comment by toebes** [comment]
I accept your comment.. however, these are the commands which resulted in getting the error above.  I will look for another repository.  

git clone --depth 1 https://github.com/mgechev/angular-seed.git
cd angular-seed
npm install
npm install -g yarn
yarn install
npm start

**Comment by gkalpak** [comment]
Yes, this is a different repo. You are looking for https://github.com/mgechev/angular-seed.git, but here is angular/angular-seed.

**Comment by toebes** [comment]
Thank you!  The only reason I came here was that it was based on the error messages coming out of that install which told me to come here to post the bugs:

> 102 error You can get information on how to open an issue for this project with:
> 102 error     npm bugs angular-seed
> 102 error Or if that isn't available, you can get their info via:
> 102 error     npm owner ls angular-seed
> 
I appreciate the pointer and have gone there to report it!
