### ISSUE TITLE
Running angular-seed in GAE

### ISSUE THREAD

**Issue by GeStanley** [angular/angular-seed#404]
Hello,
I'm wondering if anyone has any suggestions for running a simple app in google app engine.

The current start command fails because it's configured to run on localhost 8000 obviously - as per below in the package.json:

"start": "http-server -a localhost -p 8000 -c-1 ./app"

I'm wondering what I should do in order to get this runnable in appengine. Everything I've tried has resulted in a "ReferenceError: angular is not defined" error. I'm assuming I would need to create a server.js file for GAE to boot from. Does anyone have any guidance on this?

Thanks.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

##
That said, please keep in mind that `http-server` is only meant to be used during development, not on production.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by GeStanley** [comment]
I guess it's subject to interpretation. One way of interpreting this would be requesting and example server.js to allow running in production...

**Comment by gkalpak** [comment]
You don't need a `server.js` or anything to run this in production. This seed (as most AngularJS seeds) is server-side agnostic; AngularJS is a client-side framework. You can serve the static files using any webserver (e.g. Apache, nginx, etc) or create your server-side code in any language (e.g. JS, Python, PHP, Java, etc).
