### ISSUE TITLE
Error: Cannot find module '.tmp/Rx.min.js'

### ISSUE THREAD

**Issue by laurencefass** [angular/angular-seed#408]
After npm install with no errors, I cant start angular seed on my system.... the last message in the output below looks like a port error. do any modules need specific ports configured to work properly? Problem RX configuration? Thanks

> env
> ===
> vbox host: windows 10 
> vbox guest: boot2docker 
> docker host: vbox guest
> container: ubuntu 14.04
> npm: 4.2
> node: 7.8

npm start
=====
> [16:10:43] Using gulpfile /test/seed/gulpfile.ts
> [16:10:43] Starting 'serve.dev'...
> [16:10:43] Starting 'build.dev'...
> [16:10:43] Starting 'initialize'...
> [16:10:43] Starting 'noop'...
> [16:10:43] Finished 'noop' after 216 ms
> [16:10:43] Finished 'initialize' after 221 ms
> [16:10:43] Starting 'clean.once'...
> [16:10:43] Starting 'check.tools'...
> [16:10:44] Tools not compiled, skipping rebuild
> [16:10:44] Finished 'check.tools' after 469 ms
> [16:10:44] Starting 'clean.dev'...
> [16:10:44] Deleted dist/dev
> [16:10:44] Finished 'clean.dev' after 99 ms
> [16:10:44] Starting 'clean.coverage'...
> [16:10:44] Deleted coverage_js
> [16:10:44] Deleted coverage
> [16:10:44] Finished 'clean.coverage' after 120 ms
> [16:10:44] Finished 'clean.once' after 695 ms
> [16:10:44] Starting 'build.assets.dev'...
> [16:10:44] Finished 'build.assets.dev' after 418 ms
> [16:10:44] Starting 'build.html_css'...
> [16:10:51] 'build.html_css' errored after 6.09 s
> [16:10:51] Error: Cannot find module '.tmp/Rx.min.js'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.resolve (internal/module.js:27:19)
>     at /test/seed/tools/config/seed.config.ts:675:59
>     at Array.forEach (native)
>     at normalizeDependencies (/test/seed/tools/config/seed.config.ts:675:6)
>     at ProjectConfig.get [as DEPENDENCIES] (/test/seed/tools/config/seed.config.ts:355:12)
>     at getExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:139:16)
>     at getExternalCssStream (/test/seed/tools/tasks/seed/build.html_css.ts:131:19)
>     at processExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:163:10)
>     at processExternalStylesheets (/test/seed/tools/tasks/seed/build.html_css.ts:112:65)
> [16:10:51] 'serve.dev' errored after 7.47 s
> [16:10:51] Error in plugin 'run-sequence(build.html_css)'
> Message:
>     Cannot find module '.tmp/Rx.min.js'
> Details:
>     code: MODULE_NOT_FOUND
> Stack:
> Error: Cannot find module '.tmp/Rx.min.js'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.resolve (internal/module.js:27:19)
>     at /test/seed/tools/config/seed.config.ts:675:59
>     at Array.forEach (native)
>     at normalizeDependencies (/test/seed/tools/config/seed.config.ts:675:6)
>     at ProjectConfig.get [as DEPENDENCIES] (/test/seed/tools/config/seed.config.ts:355:12)
>     at getExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:139:16)
>     at getExternalCssStream (/test/seed/tools/tasks/seed/build.html_css.ts:131:19)
>     at processExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:163:10)
>     at processExternalStylesheets (/test/seed/tools/tasks/seed/build.html_css.ts:112:65)
> [16:10:51] 'build.dev' errored after 7.47 s
> [16:10:51] Error in plugin 'run-sequence(serve.dev)'
> Message:
>     Cannot find module '.tmp/Rx.min.js'
> Details:
>     code: MODULE_NOT_FOUND
> Stack:
> Error: Cannot find module '.tmp/Rx.min.js'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.resolve (internal/module.js:27:19)
>     at /test/seed/tools/config/seed.config.ts:675:59
>     at Array.forEach (native)
>     at normalizeDependencies (/test/seed/tools/config/seed.config.ts:675:6)
>     at ProjectConfig.get [as DEPENDENCIES] (/test/seed/tools/config/seed.config.ts:355:12)
>     at getExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:139:16)
>     at getExternalCssStream (/test/seed/tools/tasks/seed/build.html_css.ts:131:19)
>     at processExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:163:10)
>     at processExternalStylesheets (/test/seed/tools/tasks/seed/build.html_css.ts:112:65)
> [16:10:51] 'build.dev' errored after 7.48 s
> [16:10:51] Error in plugin 'run-sequence(build.html_css)'
> Message:
>     Cannot find module '.tmp/Rx.min.js'
> Details:
>     code: MODULE_NOT_FOUND
> Stack:
> Error: Cannot find module '.tmp/Rx.min.js'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.resolve (internal/module.js:27:19)
>     at /test/seed/tools/config/seed.config.ts:675:59
>     at Array.forEach (native)
>     at normalizeDependencies (/test/seed/tools/config/seed.config.ts:675:6)
>     at ProjectConfig.get [as DEPENDENCIES] (/test/seed/tools/config/seed.config.ts:355:12)
>     at getExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:139:16)
>     at getExternalCssStream (/test/seed/tools/tasks/seed/build.html_css.ts:131:19)
>     at processExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:163:10)
>     at processExternalStylesheets (/test/seed/tools/tasks/seed/build.html_css.ts:112:65)
> 
> npm ERR! Linux 4.4.57-boot2docker
> npm ERR! argv "/root/.nvm/versions/node/v7.8.0/bin/node" "/root/.nvm/versions/node/v7.8.0/bin/npm" "start"
> npm ERR! node v7.8.0
> npm ERR! npm  v4.2.0
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! angular-seed@0.0.0 start: `gulp serve.dev --color`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the angular-seed@0.0.0 start script 'gulp serve.dev --color'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the angular-seed package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     gulp serve.dev --color
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs angular-seed
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls angular-seed
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/.npm/_logs/2017-04-05T16_10_51_394Z-debug.log

**Comment by gkalpak** [comment]
Wrong repo. Maybe you are looking for https://github.com/mgechev/angular-seed.
