### ISSUE TITLE
npm install Error

### ISSUE THREAD

**Issue by otaruMendez** [angular/angular-seed#410]
Error Message after updating npm:

optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular-seed@0.0.0 postinstall: `bower install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

**Comment by gkalpak** [comment]
I'm afraid this is related to bower, so there is not much we can do 😞 
What is the output of `node_modules/.bin/bower install`?

**Comment by otaruMendez** [comment]
Yeah, I figured, I am new to javascript in general and didn't find any user friendly error.
