### ISSUE TITLE
newman installation on windows 

### ISSUE THREAD

**Issue by srinivasmmdl** [angular/angular-seed#412]
Hello,

I am trying to install newman on my windows 10 pro.

Step1: installed nodejs v4.5.0

C:\Users\SreeSandy\AppData\Roaming\npm>npm -v
4.5.0

When I am trying to install newman through command line I am getting the below error.

npm install newman --global or npm install newman 

from npm installation directory..

C:\Users\SreeSandy\AppData\Roaming\npm>npm install newman --global
npm ERR! not a package C:\Users\SreeSandy\AppData\Roaming\npm\newman
npm ERR! addLocal Could not install C:\Users\SreeSandy\AppData\Roaming\npm\newman
npm ERR! path C:\Users\SREESA~1\AppData\Local\Temp\npm-7652-750fbfc5\unpack-f79246f4\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\SREESA~1\AppData\Local\Temp\npm-7652-750fbfc5\unpack-f79246f4\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SreeSandy\AppData\Roaming\npm-cache\_logs\2017-05-10T05_25_19_924Z-debug.log

**Comment by gkalpak** [comment]
This issue is not related to the `angular-seed` project.
