### ISSUE TITLE
Error on Start NPM

### ISSUE THREAD

**Issue by ankurmishra1jan** [angular/angular-seed#415]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! file C:\angular2\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 27:1
npm ERR! }
npm ERR! ^
npm ERR! File: C:\angular2\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\angular2\npm-debug.log

This is my Issue any one can help me when i start my npm then it come.

**Comment by gkalpak** [comment]
You are probably looking for https://github.com/mgechev/angular-seed.
