### ISSUE TITLE
while installing npm install -g @angular/cli i'm getting this error 

### ISSUE THREAD

**Issue by prashant2k15** [angular/angular-seed#422]
version details of my windows system
C:\Users\Prashant>npm -v
5.3.0
C:\Users\Prashant>node -v
v8.2.1

C:\Users\Prashant>npm install -g @angular/cli

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by gkalpak** [comment]
This is the wrong repo (possibly looking for https://github.com/mgechev/angular-seed).
(BTW, you can ignore this error. It is just a warning.)
