### ISSUE TITLE
Not able to inject service in controller

### ISSUE THREAD

**Issue by divyachawla28** [angular/angular-seed#434]
I have tried to create a service in a separate folder and inject it into controller of custom template named login. This template works fine until I didn't inject service into its controller.But at the moment i injected service into its controller,  it didn't work.Gives the following error:

Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:modulerr] Failed to instantiate module myApp.login due to:
Error: [$injector:nomod] Module 'myApp.login' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
