### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by balajikirnakumar** [angular/angular-seed#436]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-sample@0.0.0~prestart: angular-sample@0.0.0
6 info lifecycle angular-sample@0.0.0~start: angular-sample@0.0.0
7 verbose lifecycle angular-sample@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle angular-sample@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\angular\cascadingdropdownsample\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\TortoiseHg\;C:\Users\balajin\AppData\Roaming\npm;C:\Users\balajin\AppData\Local\Programs\Git\cmd
9 verbose lifecycle angular-sample@0.0.0~start: CWD: D:\angular\cascadingdropdownsample
10 silly lifecycle angular-sample@0.0.0~start: Args: [ '/d /s /c', 'ng serve' ]
11 silly lifecycle angular-sample@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle angular-sample@0.0.0~start: Failed to exec start script
13 verbose stack Error: angular-sample@0.0.0 start: `ng serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid angular-sample@0.0.0
15 verbose cwd D:\angular\cascadingdropdownsample
16 verbose Windows_NT 10.0.10240
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error angular-sample@0.0.0 start: `ng serve`
22 error Exit status 1
23 error Failed at the angular-sample@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by gkalpak** [comment]
Sounds like this is the wrong repo. Maybe you are looking for https://github.com/angular/angular2-seed.
