### ISSUE TITLE
Unable to Access

### ISSUE THREAD

**Issue by rakeshkotha6** [angular/angular-seed#437]

**Comment by rakeshkotha6** [comment]
I have deployed this application in linux and started using npm start and tried to access from my local browser it is not accessible.

i typed http://ipaddress:port/index.html.  
When  i do  npm start in my local and app is accessible from browser as http://localhost:port/index.html. 

below are the modifications i have tried when deployed in linux

in package.json 
from
"start": "http-server -a localhost -p 8000 -c-1 ./app"
to
"start": "http-server -a 0.0.0.0 -p 8000 -c-1 ./app".

Can someone  help me how to access this application when deployed in Linux?

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
