### ISSUE TITLE
Missing instructions for how to update to angularjs 1.7

### ISSUE THREAD

**Issue by binki** [angular/angular-seed#439]
Hi,

At the [1.7.3 docs tutorial](https://code.angularjs.org/1.7.3/docs/tutorial/step_00), it recommends to use this repository. However, when I run `npm install`, it gives me angularjs-1.5.x. Also, I read the [README and it says](https://github.com/angular/angular-seed/tree/9ca17826290e8c7159eb1a2b93494a30ad083a43#updating-angular):

> Since the Angular framework library code and tools are acquired through package managers (npm and bower) you can use these tools to easily update the dependencies. Simply run the preconfigured script:
>
>     npm run update-deps

But when I do that, it says something like the following indicating that it is staying within 1.5 because they are ~ dependencies:

```
ohnobinki@gibby ~/public_html/angularjs-location-path $ npm run update-deps

> angular-seed@0.0.0 update-deps /home/ohnobinki/public_html/angularjs-location-path
> npm update


> angular-seed@0.0.0 postupdate-deps /home/ohnobinki/public_html/angularjs-location-path
> bower update

bower cached        https://github.com/angular/bower-angular-loader.git#1.5.11
bower validate      1.5.11 against https://github.com/angular/bower-angular-loader.git#~1.5.0
bower cached        https://github.com/angular/bower-angular.git#1.5.11
bower validate      1.5.11 against https://github.com/angular/bower-angular.git#~1.5.0
bower cached        https://github.com/h5bp/html5-boilerplate.git#5.3.0
bower validate      5.3.0 against https://github.com/h5bp/html5-boilerplate.git#^5.3.0
bower cached        https://github.com/angular/bower-angular-mocks.git#1.5.11
bower validate      1.5.11 against https://github.com/angular/bower-angular-mocks.git#~1.5.0
bower cached        https://github.com/angular/bower-angular-route.git#1.5.11
bower validate      1.5.11 against https://github.com/angular/bower-angular-route.git#~1.5.0

```

Could the README be updated to explain how to manually do a major (in AngularJS, 1.2 to 1.3 is considered major because it doesn’t use semver which explains why it is using ~ instead of ^ for dependencies) update?

**Comment by gkalpak** [comment]
I also added a note about upgrading in the tutorial (in angular/angular.js#16753).
