### ISSUE TITLE
Is it just me or autoreload feature is missing?

### ISSUE THREAD

**Issue by marsrobertson** [angular/angular-seed#446]
Call me old school, but I'm still using Angular 1.x

The main reason being - I can do anything and everything - no need to learn another JavaScript framework _(that will make me at most equally productive)_, I'd rather invest in AI, ML, VR, blockchain, IoT, leadership, negotiation, other soft skills, graphic design, foreign languages and physical fitness.

_(unless trainign on the job, then I can use any framework you desire)_

Just checking, cannot find LiveReload in `package.json`

```
"scripts": {
    "postinstall": "npm run copy-libs",
    "update-deps": "npm update",
    "postupdate-deps": "npm run copy-libs",
    "copy-libs": "cpx \"node_modules/{angular,angular-*,html5-boilerplate/dist}/**/*\" app/lib -C",
    "prestart": "npm install",
    "start": "http-server -a 0.0.0.0 -p 8000 -c-1 ./app",
    "pretest": "npm install",
    "test": "karma start karma.conf.js",
    "test-single-run": "npm test -- --single-run",
    "preupdate-webdriver": "npm install",
    "//": "Do not install the Firefox driver to work around https://github.com/angular/webdriver-manager/issues/303.",
    "update-webdriver": "webdriver-manager update --gecko false",
    "preprotractor": "npm run update-webdriver",
    "protractor": "protractor e2e-tests/protractor.conf.js",
    "update-index-async": "node --eval \"var fs=require('fs'),indexFile='app/index-async.html',loaderFile='app/lib/angular-loader/angular-loader.min.js',loaderText=fs.readFileSync(loaderFile,'utf-8').split(/sourceMappingURL=angular-loader.min.js.map/).join('sourceMappingURL=lib/angular-loader/angular-loader.min.js.map'),indexText=fs.readFileSync(indexFile,'utf-8').split(/\\/\\/@@NG_LOADER_START@@[\\s\\S]*\\/\\/@@NG_LOADER_END@@/).join('//@@NG_LOADER_START@@\\n'+loaderText+'    //@@NG_LOADER_END@@');fs.writeFileSync(indexFile,indexText);\""
  }
```

I'm using http://livereload.com/ so I'm sorted but I think it should be built-in with existing scripts...

**Comment by gkalpak** [comment]
This is a very basic (and probably outdated 🙊) seed project, mainly inteded for beginners. With AngularJS now [in LTS mode][1], we do not intend to keep updating or enhancing it with more features.

For a more feature-complete starter, you could use one of the popular generators or a more modern seed (such as [angularjs-webpack-starter][2]).

[1]: https://docs.angularjs.org/misc/version-support-status#long-term-support
[2]: https://github.com/frederikprijck/angularjs-webpack-starter
