### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by zackzergzeng** [angular/angular-seed#449]
when I run 'npm install',cmd show:

angular-seed@0.0.0 copy-libs C:UsersAdministratorDesktopfrontDemoangular-seed
cpx "node_modules/{angular,angular-,html5-boilerplate/dist}//" app/lib -C

Failed to copy: ENOENT: no such file or directory, chmod 'C:UsersAdministratorDesktopfrontDemoangular-seedapplibhtml5-boilerplatedistjsmain.js'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@0.0.0 copy-libs: cpx "node_modules/{angular,angular-*,html5-boilerplate/dist}/**/*" app/lib -C
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 copy-libs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I can not find the way install no error
(i am a rookie.)

**Comment by zackzergzeng** [comment]
my computer's node and npm is the latest version

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by hammondan** [comment]
@zackzergzeng did you ever resolve this? I'm seeing the same thing.

**Comment by hammondan** [comment]
I just resolved it by removing the post install script in the package.json. Not sure the ramifications of this, but it worked  for my needs.

**Comment by zackzergzeng** [comment]
@hammondan I just delete cpx command in package.json and copy those documents to /lib by my self

**Comment by zackzergzeng** [comment]
I still don't know how to solve it
