### ISSUE TITLE
fail to install ui-bootstrap

### ISSUE THREAD

**Issue by havefan-cccoder** [angular/angular-seed#452]
i cloned the project and npm start successfully.but when i want to npm install ui-bootstrap,it's not work.
➜  angular-seed git:(master) ✗ node -v
v10.15.3
➜  angular-seed git:(master) ✗ npm -v
6.4.1

> html code 

           <div class="dropdown" uib-dropdown >
    <input type="text" uib-dropdown-toggle placeholder="请选择"/><i class="fa fa-caret-down quickmodel_arrow"></i>
    <ul class="dropdown-menu" uib-dropdown-menu>
        <li>
            语文
        </li>
        <li>
            数学
        </li>
        <li>
            英语
        </li>
    </ul>
  </div>

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
